[package]
name = "rusty_mine"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "3"
members = [
    ".",
    "macros"
]

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
tokio = { version = "1.47.1", features = ["full"] }
eyre = "0.6.12"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
serde = { version = "1.0.228", features = ["derive"] }
serde-java-properties = "0.2.0"
serde_json = "1.0.145"

macros = { path = "macros" }
uuid = { version = "1.18.1", features = ["serde"] }
rsa = "0.9.8"
reqwest = { version = "0.12.23", features = ["json"] }
sha1 = "0.10.6"
num-bigint = "0.4.6"
