use crate::protocol::types::Byte;
use crate::protocol::types::Identifier;
use crate::protocol::types::Uuid;
use crate::protocol::types::{
    Boolean, ByteArray, GameProfile, PrefixedArray, PrefixedOptional, String, VarInt,
};
use macros::Packet;
use serde_json::json;

/// Disconnect client
#[derive(Debug, Packet)]
#[packet(id = 0x00)]
pub struct DisconnectClient {
    /// Json Text Component
    pub reason: String,
}

impl DisconnectClient {
    /// util to get a DisconnectClient with reason
    pub fn text(reason: std::string::String) -> Self {
        Self {
            reason: String(json!({"text": reason}).to_string()),
        }
    }
}

/// Request for encryption.
#[derive(Debug, Packet)]
#[packet(id = 0x01)]
pub struct EncryptionRequest {
    /// Server Id, should be empty like in vanilla server
    pub server_id: String,
    /// public key generated on server startup
    pub public_key: PrefixedArray<Byte>,
    /// 4 byte random to verify public key
    pub verify_token: PrefixedArray<Byte>,
    /// should request to mojang for authentication
    pub should_authenticate: Boolean,
}

/// Login Success, with profile from mojang authentication
#[derive(Debug, Packet)]
#[packet(id = 0x02)]
pub struct LoginSuccess {
    /// game profile, data from mojang authenticate server
    pub profile: GameProfile,
}

/// Set compression for connection, packet follow up should be compressed
#[derive(Debug, Packet)]
#[packet(id = 0x03)]
pub struct SetCompression {
    /// Maximum size of packet before it got compressed
    pub threshold: VarInt,
}

/// Used to implement a custom handshaking flow together with LoginPluginResponse
#[derive(Debug, Packet)]
#[packet(id = 0x04)]
pub struct LoginPluginRequest {
    /// generated by server, unique to the connection
    pub message_id: VarInt,
    /// Name of the plugin channel
    pub channel: Identifier,
    /// Any data depending on the channel
    pub data: ByteArray,
}

/// Request a cookie that was previously stored
#[derive(Debug, Packet)]
#[packet(id = 0x05)]
pub struct CookieRequest {
    /// Identifier of the cookie
    pub key: Identifier,
}

/// Start login flow
#[derive(Debug, Packet)]
#[packet(id = 0x00)]
pub struct LoginStart {
    /// player's username
    pub name: String,
    /// uuid of player logging in, unused by vanilla server
    #[allow(dead_code)]
    pub uuid: Uuid,
}

/// response to server's EncryptionRequest
#[derive(Debug, Packet)]
#[packet(id = 0x01)]
pub struct EncryptionResponse {
    /// client-generated 128-bit key used encrypt packets, encrypted with server's public key
    pub shared_secret: PrefixedArray<Byte>,
    /// verify token encrypted with server's public key, should be identical to EncryptionRequest
    pub verify_token: PrefixedArray<Byte>,
}

/// response to LoginPluginRequest
#[derive(Debug, Packet)]
#[packet(id = 0x02)]
pub struct LoginPluginResponse {
    /// should match id from server
    pub message_id: VarInt,
    /// any date, depending on the channel
    pub data: PrefixedOptional<ByteArray>,
}

/// Client acknowledging LoginSuccess, protocol state changes to Configuration after this
#[derive(Debug, Packet)]
#[packet(id = 0x03)]
pub struct LoginAcknowledged {}

/// response to CookieRequest
#[derive(Debug, Packet)]
#[packet(id = 0x04)]
pub struct CookieResponse {
    pub key: Identifier,
    pub payload: PrefixedOptional<PrefixedArray<Byte>>,
}
